### ISSUE TITLE
Ikoner på Om oss siden brukket

### ISSUE THREAD

**Issue by ivaruf** [iterate/iterate.github.com#134]
Ikoner under seksjon "Vi er gode på" laster ikke.

Testet på desktop med Chrome og Firefox. 
Funker på Mobil (Chrome).

**Comment by troubalex** [comment]
Kan du ta et skjermbilde av hvordan de ser ut for deg?

**Comment by ivaruf** [comment]
Ubuntu 14.04 LTS 64 bit

Chrome Version 45.0.2454.93 (64-bit)
![broken_icons_chrome](https://cloud.githubusercontent.com/assets/219015/12614535/d8c5e9fc-c500-11e5-9830-1de34a5a677f.png)

Firefox 40.0.3
![broken_icons_firefox](https://cloud.githubusercontent.com/assets/219015/12614534/d8c5d2a0-c500-11e5-8a55-846325ae30d0.png)

**Comment by troubalex** [comment]
Bleh. Who ships OSes without emoji font these days? I'll come up with a plan B.
