### ISSUE TITLE
All profile pics are blur on Mennesker

### ISSUE THREAD

**Issue by manzare** [iterate/iterate.github.com#138]
220 x 180 px profile pic images are framed in a 280 x 229 px mugshot thus resulting in blurry pics.
I guess we should either upload pics that are resized from a bigger image to 280 x 229 px or reset the mugshot to 220 x180

**Comment by troubalex** [comment]
We need larger images because the cards are flexible in width based on the size of the browser window. :)

**Comment by manzare** [comment]
How large images do we need? Circa pixel I mean.

**Comment by troubalex** [comment]
600px width

On Wed, 27 Jan 2016 at 15:05 Rita Jónyer <notifications@github.com> wrote:

> How large images do we need? Circa pixel I mean.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/iterate/iterate.github.com/issues/138#issuecomment-175645439>
> .
>
-- 
Alexandra Leisse
@troubalex

**Comment by troubalex** [comment]
Closed with ee37db8d96cb5dd82be82ecd526e66b815685410
