### ISSUE TITLE
Anchor links virker ikke i Firefox

### ISSUE THREAD

**Issue by fredriv** [iterate/iterate.github.com#139]
Anchor linkene ("Ta kontakt ..." på forsiden, "Bli en av oss" under karriere) virker ikke i Firefox. Mangler selve anchor-tag'en (\<a name="..."\>). Funker fint i Chrome.

Testet med Firefox 43.0.4 under Ubuntu 15.04.

**Comment by troubalex** [comment]
Something is wrong with the smooth scrolling animation. I have now corrected the HTML source and uncommented all JS, so anchors work.

Help wanted to make the animation work again. @barlindhaug, @varl or @ruudud ?
