### ISSUE TITLE
"Ta testen" under karriere fører til Google doc som ikke kan åpnes

### ISSUE THREAD

**Issue by fredriv** [iterate/iterate.github.com#140]
Får bare feilmelding fra Google om "Sorry, unable to open the file at this time"

**Comment by troubalex** [comment]
Jeg hadde det samme ørten ganger. Noe @slipset kan kanskje gjøre noe med?

**Comment by troubalex** [comment]
Med andre ord: det er den eneste lenken jeg fikk, det er noe galt med enten den eller med rettighetene.

**Comment by slipset** [comment]
Det ser ut som om `button_to` dingsen gjør en POST når man trykker på den.
Regner med at det funker som fjell dersom man får noen til å la den gjøre en GET isteden.

**Comment by slipset** [comment]
Så jeg regner med at man burde bruke `link_to` og ikke `button_to`, men da ryker sikkert designet, så jeg feiger ut og lar @troubalex gjøre det.

**Comment by klette** [comment]
Fixed

**Comment by troubalex** [comment]
:heart:
